const modules=[
["Students","🎓","Enrollment, profiles and student records"],["Teachers","👩‍🏫","Faculty profiles and assignments"],["Enrollment","📝","Admissions and registration"],["Classes & Sections","🏫","Grade levels, sections and advisers"],["Attendance","✓","Daily student attendance"],["Schedules","📅","Classes, rooms and timetables"],["Grades","📊","Grades and report cards"],["Assignments","📚","Learning tasks and submissions"],["Accounting","₱","Tuition, payments and receipts"],["Parents","👪","Parent accounts and communication"],["Announcements","📣","School-wide notices"],["Documents","📄","Certificates and school documents"],["Inventory","📦","School assets and supplies"],["Reports","📈","Academic and operational reports"],["Audit History","🕘","System activity and changes"],["Settings","⚙️","School year, users and permissions"]];
const seed={Students:[["2026-0001 · Mia Santos","Grade 7 – Rizal","Active"],["2026-0002 · Lucas Reyes","Grade 8 – Bonifacio","Active"]],Teachers:[["Ana Cruz","Mathematics · Grade 7","Active"],["Marco Lim","Science · Grade 8","Active"]],Enrollment:[["ENR-26001 · Sofia Garcia","Grade 7 application","Pending"]],Accounting:[["OR-10021 · Mia Santos","Tuition · ₱4,500","Completed"]],Announcements:[["First Quarter Examination","October 12–16, 2026","Active"]]};
let current="",data=JSON.parse(localStorage.getItem("schoolData")||"{}");Object.keys(seed).forEach(k=>data[k]??=seed[k]);function save(){localStorage.setItem("schoolData",JSON.stringify(data))}
const $=id=>document.getElementById(id);
$("loginBtn").onclick=()=>{if($("username").value==="admin"&&$("password").value==="school123"){ $("login").classList.add("hidden");$("app").classList.remove("hidden");$("roleTag").textContent=$("role").value.toUpperCase();renderHome()}else alert("Use demo login: admin / school123")};
document.querySelectorAll(".roleDemo").forEach(b=>b.onclick=()=>{$("role").value=b.dataset.role;$("username").value="admin";$("password").value="school123";$("loginBtn").click()});
$("logout").onclick=()=>location.reload();
const studentModules=[
["My Student Profile","👤","Personal Information • Student ID • Grade & Section • Adviser • Guardian Information"],
["Academics","📚","My Subjects • My Schedule • Assignments • Learning Materials"],
["Grades","📊","Current Grades • Quarterly Grades • Final Grades • Report Card • Academic History"],
["Attendance","✅","Daily Attendance • Late Records • Absences • Attendance Summary"],
["My Account","💳","Tuition Balance • Payment History • Official Receipts • Other Fees"],
["School Life","📅","School Calendar • Events • Activities • Holidays • Examination Schedule"],
["Updates","📢","Announcements • Notifications • Teacher Messages • School Messages"],
["Documents","📁","Enrollment Requirements • Certificates • School Forms • Downloadable Documents"],
["Achievements","🏆","Honors • Awards • Certificates • Recognitions"],
["Student Services","🆘","Registrar • Accounting Help • Guidance Office • Technical Help"]
];
function renderHome(){const isStudent=$("role").value==="Student";const activeModules=isStudent?studentModules:modules;$("orbitShell").classList.toggle("studentOrbit",isStudent);$("orbitRole").textContent=isStudent?"STUDENT":"SCHOOL";$("orbitTitle").textContent="COMMAND CENTER";$("stats").innerHTML=[["1,248","Students"],["68","Teachers"],["42","Classes"],["96%","Attendance"]].map(x=>'<div class="stat"><b>'+x[0]+'</b><span>'+x[1]+'</span></div>').join("");$("modules").innerHTML=activeModules.map((m,i)=>'<div class="module" data-i="'+i+'"><i>'+m[1]+'</i><h3>'+m[0]+'</h3><p>'+m[2]+'</p></div>').join("");document.querySelectorAll(".module").forEach(x=>x.onclick=()=>openModule(activeModules[x.dataset.i][0]))}
function openModule(name){current=name;data[current]??=[];$("home").classList.add("hidden");$("workspace").classList.remove("hidden");$("wsTitle").textContent=name;$("search").value="";renderRows()}
$("back").onclick=()=>{$("workspace").classList.add("hidden");$("home").classList.remove("hidden")};
function renderRows(){let q=$("search").value.toLowerCase(),rows=(data[current]||[]).filter(r=>r.join(" ").toLowerCase().includes(q));$("content").innerHTML='<div class="table"><table><thead><tr><th>Record</th><th>Details</th><th>Status</th><th></th></tr></thead><tbody>'+ (rows.length?rows.map((r,i)=>'<tr><td><b>'+r[0]+'</b></td><td>'+r[1]+'</td><td><span class="pill">'+r[2]+'</span></td><td><button class="del" data-name="'+encodeURIComponent(r[0])+'">Delete</button></td></tr>').join(""):'<tr><td colspan="4">No records yet. Tap “Add Record”.</td></tr>')+'</tbody></table></div>';document.querySelectorAll(".del").forEach(b=>b.onclick=()=>{let n=decodeURIComponent(b.dataset.name);data[current]=data[current].filter(r=>r[0]!==n);save();renderRows()})}
$("search").oninput=renderRows;$("addBtn").onclick=()=>{$("modal").classList.remove("hidden");$("formTitle").textContent="Add "+current+" Record";$("fName").focus()};$("cancel").onclick=()=>$("modal").classList.add("hidden");$("recordForm").onsubmit=e=>{e.preventDefault();data[current].push([$("fName").value,$("fDetails").value,$("fStatus").value]);save();e.target.reset();$("modal").classList.add("hidden");renderRows()};